name: Run Selenium script

on: [push]

jobs:
  run-selenium-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        mv -f chromedriver /usr/local/bin/chromedriver
        chown root:root /usr/local/bin/chromedriver
        chmod 0755 /usr/local/bin/chromedriver

    - name: Set up Xvfb
      run: Xvfb :99 -ac &

    - name: Run Selenium script
      env:
        DISPLAY: :99
        PATH: /usr/local/bin:$PATH
        CHROME_BIN: /usr/bin/google-chrome
        CHROME_PATH: /usr/bin/google-chrome
      run: python new.py
