name: Code Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  autopep8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
        
    - name: Check for uncommitted changes
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "There are uncommitted changes";
          exit 1;
        else
          echo "No uncommitted changes";
        fi
